name: Basic Linter

on:
  push:
    branches:
      - main

jobs:
  run-linters:
    name: Run Linter
    runs-on: ubuntu-latest

    steps:
    - task: Bash@3
      displayName: 'Lint Users file'
      inputs:
        filePath: 'src/linter.sh'
        failOnStderr: true