
name: Automated website deploy status
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@v1
    - name: Lint Submission
      working-directory: ./src
      run: ./linter.sh
      shell: bash
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.0.100'
    - name: Login to Azure
      uses: azure/login@v1
      with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: Upload files
      uses: azure/CLI@v1
      with:
        inlineScript: |
            az storage blob upload-batch --account-name reespozzi --overwrite true --auth-mode key -d '$web' -s .
            az storage blob copy start --account-name reespozzi --auth-mode key --destination-blob . --destination-container '$web' --source-uri https://reespozzi.blob.core.windows.net/$web/src/index.html
    # logout of azure
    - name: Log out and finish
      run: |
            az logout
      if: always()
    # logout of azure
    - name: Site available
      run: |
            echo "https://reespozzi.z13.web.core.windows.net/"